//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offlineMessagingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {

        public ExceptionLog(Exception e)
        {
            this.Message = e.Message;
            this.Source = e.Source;
            this.StackTrace = e.StackTrace;
            this.Time = DateTime.Now;
        }

        public int Id { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime Time { get; set; }
    }
}
