//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace offlineMessagingAPI
{
     public interface IStoreAppContext
    {
        DbSet<AspNetBlockedUser> AspNetBlockedUsers { get; }
        DbSet<AspNetUserMessage> AspNetUserMessages { get; }
        DbSet<ExceptionLog> ExceptionLogs { get;  }

        int SaveChanges();
    }
}