//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offlineMessagingAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlockedUsersAndMessages : DbContext, IStoreAppContext
    {
        public BlockedUsersAndMessages()
            : base("name=BlockedUsersAndMessages")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetBlockedUser> AspNetBlockedUsers { get; set; }
        public virtual DbSet<AspNetUserMessage> AspNetUserMessages { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
    }
}
